### ISSUE TITLE
Floating callouts doesn`t work properly on Minimal Theme

### ISSUE THREAD

**Issue by ka1tzyu** [efemkay/obsidian-modular-css-layout#3] opened 2022-04-25 17:55 UTC
I switched on last version of css snippet called "MCL Multi Column.css". I also specified `text-justify` css class in the YAML metadata.

Firstly I tried to add `blank-container` callout in another callout and this way works properly:

![image](https://user-images.githubusercontent.com/56955307/165143542-9345d6f8-8e70-442a-b0a8-0b79e0a4d31a.png)

Secondly I put same `blank container` callout in usual text, and it`s not "floating" paragraphs:

![image](https://user-images.githubusercontent.com/56955307/165143961-2c88614b-25f2-40f9-ad05-577af57b1cfe.png)
![image](https://i.imgur.com/wcXpRSD.png)

I noticed only one difference between these cases, second has div wrapper on obsidian level:

![image](https://user-images.githubusercontent.com/56955307/165144312-5e98b2ef-9f36-4d0a-8603-ccc0e7630b3f.png)

And this is first works:

![image](https://i.imgur.com/DUgdRun.png)

I have suspicion to Minimal Theme, because on default theme it works nice. But disabling Minimal\`s styles for `.el-div` doesn\`t help.

> My setup:
> Obsidian v0.14.6

**Comment by efemkay** [comment] 2022-04-26 01:06
thanks @ka1tzyu for issue report. i managed to repro it as well (btw, i love your effort to test it with several scenarios). on that note, `text-justify` on the yaml is just to justify the text -- it has no effect on the layout.

anyway, i thought this could be a quick fix but i couldn't (yet) figure out what kepano did with the theme that makes it behave quite differently than other themes for float. so we'll keep it as open issue for now. but if you happen to figure out before i do, let me know.

**Comment by ka1tzyu** [comment] 2022-04-28 19:54
I found out that disabling "Contextual Typography" plugin fix the issue. But it's mainly used for minimal theme styling and only provides a bunch of special selectors. It doesn't provide any css. I spent some time to realize a reason of this issue. 

The Contextual Typography plugin surrounds note content by flex container. As it turned out, float and clear don't work inside flex containers. It has described [here](https://www.w3.org/TR/css-flexbox-1/#flex-containers). I have tried to avoid this limitation but it doesn't work.

So there is two possible ways to fix it:
1. Move all existing styles to flex instead of float
2. Disable Contextual Typography (it'll disable a lot of features)

**Comment by efemkay** [comment] 2022-04-29 02:12
Thanks for this insight! Due to how Obsidian structure their DOM, it is difficult to flex without wrapping it in a invisible callout (which i feel a bit much of a hack, imagine putting notes in cluster of callout). On the contextual typography, some of my snippets also uses that plugin to affect the layout.

Anyway, maybe i can try to have a workaround for minimal theme. Thanks for the info.

**Comment by ka1tzyu** [comment] 2022-04-29 13:49
I have one hack idea — create another callout wrapper fot the text with floating needs. As noticed in first issue message — float works nice in another callout. So I have idea to create callout with styles that similar to ordinary content block. But it seems to be a lot of movements for that problem's kind I think

**Comment by efemkay** [comment] 2022-05-06 02:09
okay, i don't see any other way but to revert the flex layout introduced by minimal theme. i've included cssclass / css helper `minimal-float` so that you can choose to enable it on per note basis. i'll close this issue in two weeks time if there no further issue arise from the "fix"

![image](https://user-images.githubusercontent.com/42369515/167055125-15dd0c88-70ba-4022-bf69-e8216cb36299.png)

**Comment by ka1tzyu** [comment] 2022-05-06 15:58
Unfortunately I still have troubles

![image](https://user-images.githubusercontent.com/56955307/167169227-3370e1db-15b4-4021-beb9-a6a82589c538.png)
![image](https://user-images.githubusercontent.com/56955307/167169258-85733b54-3cef-4055-a173-122f80f06e18.png)

**Comment by NB574** [comment] 2022-05-07 06:22
I can confirm that the cssclass fix works for me using Minimal, tyvm.

**Comment by ka1tzyu** [comment] 2022-05-07 08:01
> Unfortunately I still have troubles
> 
> I updated css and enabled `minimal-float`
> 
> ![image](https://user-images.githubusercontent.com/56955307/167169227-3370e1db-15b4-4021-beb9-a6a82589c538.png) ![image](https://user-images.githubusercontent.com/56955307/167169258-85733b54-3cef-4055-a173-122f80f06e18.png)

It was my fault, `minimal-float` really works

**Closed** 2022-05-21 00:17 UTC
